### ISSUE TITLE
Golden Pickaxe can't break Diamond

### ISSUE THREAD

**Issue by tobiko13** [seagemgames/tangymines#14]
After obtaining the Gold Pickaxe, the Diamond Pickaxe is the next Pickaxe to unlock. But it is apparently not possible to break diamond using a Gold Pickaxe, according to someone that has the Gold Pickaxe.

**Comment by saismeesaimonsaimes** [comment]
Thank's for letting me know, this has been fixed in dev, and will be added next update.
