### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by ghost** [seagemgames/tangymines#3]

**Comment by saismeesaimonsaimes** [comment]
Please give a description on what you mean

**Comment by ghost** [comment]
Make quest like mine 39 diamond and 10 sapphire that give you rewards such as gold or like a recepy to craft special things

**Comment by ElohGame** [comment]
My quests suggestion :
1.10dirts
2.10stones and 50dirts
3. 5coals and 100 stones
4.10 coppers 
5. 50coals
6.10irons and 5wormites
7.150Compressed Rocks
8. 65Pyrites and 65Golds
9. 50Sapphires and 15diamonds
10. 20Obsidians and 50diamonds
11. 7Rubys
12. 30Energetic Magma and 30Quartz
13. 25 Zombites and 10 Orichalcum
14. 8Mithril and 20 Orichalcum
15.3Unobtanium
16.1Demonite

Reward :
1.2irons
2.10coal and 5 irons
3.20coal 
4.10coppers
5.2golds and 15irons
6.15wormites
7.1dirts
8.50golds and 15diamonds
9.50 améthyste
10. 100diamonds
11. 5zombites
12. 15mythril
13. 1unobtanium
14.3unobtanium
15.50 rubys and 1Demonite
16. 10Demonite

**Comment by CarrierOfChaos** [comment]
It could give money
